### ISSUE TITLE
其实可以考虑写一版 Notebook 的

### ISSUE THREAD

**Issue by miRoox** [wuyudi/Effective-Mathematica#3]
毕竟 Notebook 可以说是 Mathematica 特色，而且有 [Wolfram GitHub Viewer](https://www.wolframcloud.com/obj/github-cloud/form/BadgeCreation) 可以用，都不用花自己的云积分，虽然可能速度堪忧。[这是](https://www.wolframcloud.com/obj/github-cloud/commits/efa585145394c6eb24a9ee61c0c55c2f81104fc4)一个预览。

**Comment by asukaminato0721** [comment]
这个速度😅，有点感人啊。
目前算是有几个选项
1. md，就是我目前在写的。
2. jupyter，渲染速度中等，但是写起来没有 nb 舒服。
3. nb，渲染速度感人。

所以除非做一个 workflow 啥的，自动 nb 转 jupyter 转 md，一份顶 3 份。

> 好像另一个咕咕咕很久的项目也能用到？等假期看看吧。

感觉内容太少了，又暂时想不出别的可以写的主题，就先把工具研究一下吧。
